###  Turn on lights at sunset  ###
###  [IF HOME] ###
###  [Lights] [Turn On] Lamp and Hallways  ###
group:
  living_room:
    - switch.lamp
    - light.downstairs_hallway
    - light.upstairs_hallway

automation:
  alias: Turn on light when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room
