# Sky #
- alias: 'BBC One'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'BBC One'
  action:
    service: shell_command.bbcone
- alias: 'BBC Two'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'BBC Two'
  action:
    service: shell_command.bbctwo
- alias: 'ITV'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'ITV'
  action:
    service: shell_command.itv
- alias: 'Channel 4'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'Channel 4'
  action:
    service: shell_command.channel4
- alias: 'Sky 1'
  trigger:
    - platform: state
      entity_id: input_select.channel
      state: 'Sky 1'
  action:
    service: shell_command.sky1
